# -*- coding: utf-8 -*-
"""evermore.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1og0khF4NabnlJ0oUoiUX11EkLMtuN3wN
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import nltk
from wordcloud import WordCloud
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36'}

r = 1
lyrics = []
for thing in range(15):
  url = 'https://mojim.com/twy105095x31xr.htm'
  url = url.replace('r',str(r))
  res = requests.get(url, headers=headers)
  soup = BeautifulSoup(res.text, 'html.parser')
  lyric = soup.select('.fsZx1')
  t = []
  for i in lyric:
    clean = i.text
    t.append(clean)
  lyrics.append(t)
  if thing == 14:
    break
  r += 1

len(lyrics)

lyrics

clean_needed = []
for song in lyrics:
  for i in song:
    new = i.replace('\n','').replace('Taylor Swift','').replace('更多更詳盡歌詞 在 ※ Mojim.com\u3000魔鏡歌詞網','')
    clean_needed.append(new)
clean_needed

df = pd.DataFrame(clean_needed)
df

#make a new list and make every article lower and put them in li_n
lowercase = []
for line in df[0]:
    lowercase.append(line.lower())

lowercase[1]

#stopwords setting
nltk.download('stopwords')
nltk_stopwords= nltk.corpus.stopwords.words('english')

#punctuation remove setting
import string
string.punctuation

from nltk import wordpunct_tokenize

final = []
for article in lowercase:
    punct_token = wordpunct_tokenize(article)
    #remove stopwords
    punct_token = [word for word in punct_token if word not in nltk_stopwords]
    #remove string.punctuation
    punct_token = [word for word in punct_token if word not in string.punctuation]
    #remove word that is not alphabat or number
    punct_token = [word for word in punct_token if word.isalnum()==True] #判定字詞是否為字母或數字
    final.append(punct_token)

final

word_count = {}
for sentence in final:
  for word in sentence:
    if word not in word_count:
      word_count[word] = 1
    else:
      word_count[word] += 1

#sort
pd.DataFrame([word_count]).T.sort_values(by=0,ascending=False).head(10)

import matplotlib.pyplot as plt
from wordcloud import WordCloud
wc = WordCloud(background_color="black", 
               max_words = 2000)        
with open("evermore.txt", "w") as f1:
    for line in final:
        test=','.join(line)
        f1.write(test)
text = open("evermore.txt").read()

wc.generate(text)
plt.imshow(wc)
plt.axis("off")
plt.figure(figsize=(10,6), dpi = 100)
plt.show()